Repository freediving-community/api-server, pull requests merged in 2024-04, with the labels that each got.

#111 feat: #106 - 유저 탈퇴 기능 추가
  .gitignore
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/DeleteUserController.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/DeleteUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/FindUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaEntity.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepository.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserLicenseJpaEntity.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserLicenseJpaRepository.java
  member-service/src/main/java/com/freediving/memberservice/application/port/in/DeleteUserUseCase.java
  member-service/src/main/java/com/freediving/memberservice/application/port/out/DeleteUserPort.java
  member-service/src/main/java/com/freediving/memberservice/application/service/DeleteUserService.java
  member-service/src/main/java/com/freediving/memberservice/application/service/FindUserService.java
  member-service/src/main/java/com/freediving/memberservice/domain/LicenseStatus.java
  member-service/src/main/java/com/freediving/memberservice/domain/User.java
  member-service/src/main/java/com/freediving/memberservice/domain/UserStatus.java
Labels: ✨ Feature

#114 bug: #113 - 멤버 서비스 테스트 모킹 추가
  member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
Labels: 🐞 Bug

#117 #113 - 멤버 서비스 GCP 배포 작업
  .github/workflows/member-service-gcp.yml
  .gitignore
  member-service/Dockerfile
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/OauthController.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KakaoOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/OauthUseCase.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/OauthFeignPort.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/OauthRedirectUrlPort.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/OauthTemplate.java
  member-service/src/main/java/com/freediving/authservice/application/service/OauthService.java
  member-service/src/main/java/com/freediving/authservice/config/GoogleOauthConfig.java
  member-service/src/main/java/com/freediving/authservice/config/KakaoOauthConfig.java
  member-service/src/main/java/com/freediving/authservice/config/NaverOauthConfig.java
  member-service/src/main/resources/application-local.yml
Labels: 🔨 Refactor, 🌏 Deploy

#128 다이빙 풀 데이터 확장 및 조회 개발
  buddy-service/src/main/java/com/freediving/divingpool/config/enumerate/DetailLevel.java
  buddy-service/src/main/java/com/freediving/divingpool/controller/DivingPoolController.java
  buddy-service/src/main/java/com/freediving/divingpool/data/dao/DivingPoolJpaEntity.java
  buddy-service/src/main/java/com/freediving/divingpool/data/dto/DivingPoolListResponse.java
  buddy-service/src/main/java/com/freediving/divingpool/data/dto/DivingPoolResponse.java
  buddy-service/src/main/java/com/freediving/divingpool/data/dto/DivingPoolSimpleResponse.java
  buddy-service/src/main/java/com/freediving/divingpool/repository/DivingPoolRepository.java
  buddy-service/src/main/java/com/freediving/divingpool/service/DivingPoolService.java
  buddy-service/src/main/resources/data.sql
  buddy-service/src/main/resources/schema.sql
  buddy-service/src/test/java/com/freediving/divingpool/service/DivingPoolServiceTest.java
Labels: ✨ Feature
