Repository freediving-community/api-server, pull requests merged in 2024-01, with the labels that each got.

#52 feat: Swagger UI 통합
  gateway-service/build.gradle
  gateway-service/src/main/resources/application-local.yml
Labels: ✨ Feature

#58 #57 - 소셜 로그인 기능 주석 추가 및 일부 응답 값 추가
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/OauthController.java
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/UserLoginResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/UserLoginResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/OauthResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleInfoResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleTokenResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KaKaoTokenResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KakaoInfoResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KakaoOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverInfoResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverTokenResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/service/MemberExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/JwtTokenUseCase.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/JwtTokenUtils.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/OauthUseCase.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/OauthFeignPort.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/OauthRedirectUrlPort.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/OauthTemplate.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/service/MemberFeignPort.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/service/MemberServiceFeignClient.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/service/MemberUseCase.java
  member-service/src/main/java/com/freediving/authservice/application/service/OauthService.java
  member-service/src/main/java/com/freediving/authservice/domain/OauthUser.java
Labels: 📃 Docs, ✨ Feature

#60 docs: 버디 이벤트 생성 API 스웨거 정보 추가.
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/v1/CreateBuddyEventControllerV1.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/v1/CreateBuddyEventRequestV1.java
  buddy-service/src/main/java/com/freediving/buddyservice/domain/CreatedBuddyEvent.java
  buddy-service/src/main/resources/application-local.yml
Labels: 📃 Docs

#61 #59 - MemberService Swagger 초기 설정
  gateway-service/src/main/resources/application-local.yml
  member-service/build.gradle
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/OauthController.java
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/UserLoginResponse.java
  member-service/src/main/java/com/freediving/memberservice/config/SwaggerConfig.java
  member-service/src/main/resources/application-local.yml
Labels: 📃 Docs, ✨ Feature

#63 feat: #41 - MemberService CodeDeploy 설정 추가
  .github/workflows/member-service.yml
  member-service/appspec.yml
  member-service/scripts/deploy.sh
Labels: ✨ Feature, 🌏 Deploy

#64 #41 - MemberService CI & CD 구축
  .github/workflows/member-service.yml
  member-service/scripts/deploy.sh
Labels: ✨ Feature, 🌏 Deploy

#67 #66 - AWS PreSigned Url 생성 기능 개발
  .github/workflows/member-service.yml
  member-service/build.gradle
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/ImgController.java
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/dto/CreateImgRequest.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/aws/AwsImgExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/CreateImgCommand.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/ImgUseCase.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/ImgUtils.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/ImgPort.java
  member-service/src/main/java/com/freediving/authservice/application/service/ImgService.java
  member-service/src/main/java/com/freediving/authservice/config/AwsConfig.java
  member-service/src/main/java/com/freediving/authservice/config/AwsConfigProperties.java
  member-service/src/main/resources/application-local.yml
Labels: ✨ Feature

#78 #75 - MemberService 유저 단위 테스트 작성
  member-service/build.gradle
  member-service/src/main/java/com/freediving/MemberServiceApplication.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserRequest.java
  member-service/src/main/java/com/freediving/memberservice/config/ConfigurationPropertyConfig.java
  member-service/src/main/java/com/freediving/memberservice/config/DiscoveryConfig.java
  member-service/src/main/java/com/freediving/memberservice/config/FeignConfig.java
  member-service/src/main/java/com/freediving/memberservice/config/JpaConfig.java
  member-service/src/test/java/com/freediving/memberservice/adapter/in/web/CreateUserControllerUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/adapter/in/web/FindUserControllerUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepositoryTest.java
  member-service/src/test/java/com/freediving/memberservice/application/port/in/CreateUserCommandUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/application/service/CreateUserServiceUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/custom/WithMockCustomUser.java
  member-service/src/test/java/com/freediving/memberservice/custom/WithMockCustomUserSecurityContextFactory.java
  member-service/src/test/java/com/freediving/memberservice/fixture/CreateUserCommandFixture.java
  member-service/src/test/java/com/freediving/memberservice/fixture/SecurityContextFixture.java
  member-service/src/test/java/com/freediving/memberservice/fixture/UserFixture.java
Labels: ✅ Test

#79 #75 - Configuration basePackages 지정
  member-service/src/main/java/com/freediving/memberservice/config/ConfigurationPropertyConfig.java
  member-service/src/main/java/com/freediving/memberservice/config/DiscoveryConfig.java
  member-service/src/main/java/com/freediving/memberservice/config/FeignConfig.java
Labels: 🔨 Refactor
