Repository freediving-community/api-server, pull requests merged in 2024-06, with the labels that each got.

#171 feat: 버디 참여자 정보 제공
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/internallservice/query/InternalController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/query/BuddyEventAttributeController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/externalservice/member/userinfo/MemberServiceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/BuddyEventPersistenceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/concept/BuddyEventConceptMappingPersistenceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/concept/querydsl/BuddyEventConceptMappingRepoDSL.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/concept/querydsl/BuddyEventConceptMappingRepoDSLImpl.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/divingpool/BuddyEventDivingPoolMappingPersistenceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/divingpool/querydsl/BuddyEventDivingPoolMappingRepoDSL.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/divingpool/querydsl/BuddyEventDivingPoolMappingRepoDSLImpl.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/join/BuddyEventJoinPersistenceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/join/querydsl/BuddyEventJoinRepoDSL.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/join/querydsl/BuddyEventJoinRepoDSLImpl.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/listing/GetBuddyEventListingRepoDSL.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/listing/GetBuddyEventListingRepoDSLImpl.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/internalservice/query/InternalUseCase.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/Internalservice/query/MemberStatus.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/Internalservice/query/RequestMemberPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/BuddyEventConceptMappingPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/BuddyEventDivingPoolMappingPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/BuddyEventJoinPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/GetBuddyEventCarouselPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/GetBuddyEventListingPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/Internalservice/InternalService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/CreateBuddyEventService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventCarouselService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventListingService.java
  buddy-service/src/main/java/com/freediving/divingpool/controller/DivingPoolInternalController.java
  buddy-service/src/test/java/com/freediving/buddyservice/application/service/CreateBuddyEventServiceTest.java
Labels: ✨ Feature

#175 Feat/#170 사용자 정보 상태 체크
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/internallservice/query/InternalController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/command/BuddyEventCommandController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/query/BuddyEventQueryController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/externalservice/member/userinfo/MemberServiceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/externalservice/member/userinfo/dto/UserInfo.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/listing/GetBuddyEventListingQueryProjectionDto.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/listing/GetBuddyEventListingRepoDSLImpl.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/BuddyEventDetailService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/BuddyEventLikeToggleService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/CreateBuddyEventService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventCarouselService.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventListingService.java
  buddy-service/src/main/java/com/freediving/buddyservice/config/enumerate/UserStatus.java
  common/src/main/java/com/freediving/common/handler/exception/ServiceExceptionHandler.java
Labels: ✨ Feature

#177 refactor: #162 - 유저 마이페이지 조회 API 응답 중복 데이터 제거
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/FindMyPageResponse.java
Labels: 🔨 Refactor

#178 Feat/#163
  .github/workflows/community-service-gcp.yml
  community-service/build.gradle
  community-service/src/main/java/com/freediving/communityservice/adapter/in/dto/ArticleWriteRequest.java
  community-service/src/main/java/com/freediving/communityservice/adapter/in/web/UserProvider.java
  community-service/src/main/java/com/freediving/communityservice/adapter/in/web/UserProviderArgumentResolver.java
  community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/ArticleCommandController.java
  community-service/src/main/java/com/freediving/communityservice/adapter/in/web/command/UserReactionCommandController.java
  community-service/src/main/java/com/freediving/communityservice/adapter/in/web/query/ArticleQueryController.java
  community-service/src/main/java/com/freediving/communityservice/adapter/in/web/query/BoardQueryController.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/article/ArticleBriefDto.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/dto/user/UserInfo.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/external/MemberServiceAdapter.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/external/MemberServiceClient.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticleJpaEntity.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticlePersistenceAdapter.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/article/ArticlePersistenceMapper.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/board/BoardPersistenceAdapter.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/comment/CommentPersistenceAdapter.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/constant/BoardType.java
  community-service/src/main/java/com/freediving/communityservice/adapter/out/persistence/userreact/UserReactionPersistenceAdapter.java
  community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleIndexListCommand.java
  community-service/src/main/java/com/freediving/communityservice/application/port/in/ArticleWriteCommand.java
  community-service/src/main/java/com/freediving/communityservice/application/port/out/ArticleReadPort.java
  community-service/src/main/java/com/freediving/communityservice/application/port/out/external/MemberFeignPort.java
  community-service/src/main/java/com/freediving/communityservice/application/service/ArticleService.java
  community-service/src/main/java/com/freediving/communityservice/application/service/BoardService.java
  community-service/src/main/java/com/freediving/communityservice/application/service/UserReactionService.java
  community-service/src/main/java/com/freediving/communityservice/config/CaffeineCacheConfig.java
  community-service/src/main/java/com/freediving/communityservice/config/type/CacheType.java
  community-service/src/main/java/com/freediving/communityservice/domain/Article.java
  community-service/src/main/java/com/freediving/communityservice/domain/Comment.java
  community-service/src/main/resources/data-for-PostgreSQL.sql
Labels: ✨ Feature

#185 deploy: #184 - 멤버서비스 githubactions gcp 이관 작업
  .github/workflows/member-service-gcp.yml
Labels: 🌏 Deploy

#186 deploy: #184 - 멤버서비스 githubactions gcp 이관 작업 테스트
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/CreateImgController.java
Labels: 🌏 Deploy
