Repository freediving-community/api-server, pull requests merged in 2024-05, with the labels that each got.

#140 bug: #139 - 사용자 조회 쿼리 오류 수정
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/FindUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserLicenseJpaRepository.java
Labels: 🐞 Bug

#142 refactor: #141 - 소셜로그인 유저 식별값 변경(이메일 -> 회원번호)
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/OauthResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleInfoResponse.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/google/GoogleOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/kakao/KakaoOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/external/naver/NaverOauthExternalAdapter.java
  member-service/src/main/java/com/freediving/authservice/domain/OauthUser.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/CreateUserController.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserRequest.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaEntity.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepository.java
  member-service/src/main/java/com/freediving/memberservice/application/port/in/CreateUserCommand.java
  member-service/src/test/java/com/freediving/memberservice/adapter/in/web/CreateUserControllerUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapterUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/adapter/out/persistence/UserJpaRepositoryTest.java
  member-service/src/test/java/com/freediving/memberservice/application/port/in/CreateUserCommandUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/application/service/CreateUserServiceUnitTest.java
  member-service/src/test/java/com/freediving/memberservice/fixture/CreateUserCommandFixture.java
  member-service/src/test/java/com/freediving/memberservice/fixture/UserFixture.java
Labels: 🔨 Refactor

#144 refactor: #143 - 서비스간 라우팅 URI 변경 (service -> internal)
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/DeleteImgController.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/FindUserController.java
  member-service/src/main/java/com/freediving/memberservice/config/SecurityConfig.java
  member-service/src/main/java/com/freediving/memberservice/filter/CustomAuthenticationFilter.java
  member-service/src/test/java/com/freediving/memberservice/adapter/in/web/FindUserControllerUnitTest.java
Labels: 🔨 Refactor

#146 refactor: #145 - 스웨커 토큰 업데이트 API 예시 변경
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/TokenController.java
Labels: 🔨 Refactor

#152 #145 - 유저 조회 Swagger 변경 및 로컬 테스트 유저 생성 기능 추가
  common/src/main/java/com/freediving/common/domain/member/Diving.java
  common/src/main/java/com/freediving/common/domain/member/FreeDiving.java
  common/src/main/java/com/freediving/common/domain/member/MemberLicenseInfo.java
  common/src/main/java/com/freediving/common/response/dto/member/MemberFindUserResponse.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/FindUserController.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/CreateUserRequest.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/FindUserResponse.java
  member-service/src/main/java/com/freediving/memberservice/config/SwaggerResponse.java
  member-service/src/main/java/com/freediving/memberservice/util/TestUserCreator.java
Labels: 🔨 Refactor, ✨ Feature

#156 feat: #145 - local 환경 테스트 유저 생성 기능 추가
  member-service/src/main/java/com/freediving/authservice/adapter/in/web/TokenController.java
  member-service/src/main/java/com/freediving/authservice/adapter/out/persistence/token/FindTokenPersistenceAdapter.java
  member-service/src/main/java/com/freediving/authservice/application/port/in/TokenUseCase.java
  member-service/src/main/java/com/freediving/authservice/application/port/out/FindTokenPort.java
  member-service/src/main/java/com/freediving/authservice/application/service/TokenService.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/HelloController.java
  member-service/src/main/java/com/freediving/memberservice/application/port/in/FindUserUseCase.java
  member-service/src/main/java/com/freediving/memberservice/application/service/FindUserService.java
  member-service/src/main/java/com/freediving/memberservice/util/TestUserCreator.java
Labels: ✨ Feature

#157 feat: #145 - 비로그인 API 요청 기능 추가 (Header User 정보 추가)
  gateway-service/src/main/java/org/freediving/gatewayservice/filter/AuthorizationFilter.java
  member-service/src/main/java/com/freediving/memberservice/filter/CustomAuthenticationFilter.java
Labels: ✨ Feature

#161 feat: 버디 이벤트 좋아요 설정/해지 결과 규격 수정
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/command/BuddyEventCommandController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/likecount/BuddyEventLikePersistenceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/web/command/like/BuddyEventLikeToggleUseCase.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/command/like/BuddyEventLikeTogglePort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/BuddyEventLikeToggleService.java
Labels: ✨ Feature

#164 #162 - 유저 정보 수정 / 등록 기능 추가
  member-service/build.gradle
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/UpdateUserController.java
  member-service/src/main/java/com/freediving/memberservice/adapter/in/web/dto/UpdateUserInfoRequest.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/dto/UserConceptRequest.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/dto/UserPoolRequest.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/kafka/UserPreferencesProducer.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/CreateUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/adapter/out/persistence/UpdateUserPersistenceAdapter.java
  member-service/src/main/java/com/freediving/memberservice/application/port/in/UpdateUserInfoCommand.java
  member-service/src/main/java/com/freediving/memberservice/application/port/in/UpdateUserUseCase.java
  member-service/src/main/java/com/freediving/memberservice/application/port/out/UpdateUserPort.java
  member-service/src/main/java/com/freediving/memberservice/application/service/UpdateUserService.java
  member-service/src/main/resources/application-local.yml
Labels: ✨ Feature

#166 feat: 캐로셀 타입 버디모임 조회 개발
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/in/web/query/BuddyEventQueryController.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/BuddyEventPersistenceAdapter.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/carousel/GetBuddyEventCarouselRepoDSL.java
  buddy-service/src/main/java/com/freediving/buddyservice/adapter/out/persistence/event/querydsl/carousel/GetBuddyEventCarouselRepoDSLImpl.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/web/query/home/GetBuddyEventCarouselUseCase.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/web/query/home/GetHomeActiveBuddyEventCommand.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/in/web/query/home/GetHomePreferencePoolBuddyEventCommand.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/port/out/web/query/GetBuddyEventCarouselPort.java
  buddy-service/src/main/java/com/freediving/buddyservice/application/service/web/GetBuddyEventCarouselService.java
Labels: ✨ Feature
